language: ruby
rvm:
  - 2.1.1

install:
  - export PATH=$HOME/.local/bin:$PATH
  - gem install jekyll
  - gem install jekyll-sitemap
  - gem install jekyll-paginate
  - gem install redcarpet
script:
  - jekyll build

branches:
  only:
    - master
